apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: food-to-go
build:
  artifacts:
    - image: astra-studio/food-auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: astra-studio/food-gateway
      context: gateway
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: "**/.meshrc.yaml"
deploy:
  logs:
    jsonParse:
      fields: ["message", "severity"]
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/gateway-depl.yaml
  helm:
    releases:
      - name: traefik
        upgradeOnChange: true
        repo: https://traefik.github.io/charts
        remoteChart: traefik
        namespace: traefik
        createNamespace: true
        valuesFiles:
          - "infra/k8s/charts/traefik/values.yaml"
      - name: opensearch-operator
        repo: https://opensearch-project.github.io/opensearch-k8s-operator/
        remoteChart: opensearch-operator
        namespace: opensearch
        createNamespace: true
      - name: opensearch-dashboards
        repo: https://opensearch-project.github.io/helm-charts
        remoteChart: opensearch-dashboards
        namespace: opensearch
        createNamespace: true
      - name: opensearch
        repo: https://opensearch-project.github.io/helm-charts
        remoteChart: opensearch
        namespace: opensearch
        createNamespace: true
      - name: fluentd
        repo: https://fluent.github.io/helm-charts
        remoteChart: fluentd
        namespace: fluentd
        createNamespace: true
