apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor-depl
spec:
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor
          image: casbin/casdoor-all-in-one
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: casdoor-srv
spec:
  selector:
    app: casdoor
  ports:
    - name: casdoor
      protocol: TCP
      port: 3000
      targetPort: 3000