apiVersion: apps/v1
kind: Deployment
metadata:
  name: meals-depl
spec:
  selector:
    matchLabels:
      app: meals
  template:
    metadata:
      labels:
        app: meals
    spec:
      containers:
        - name: meals
          image: astra-studio/food-meals
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: meals-srv
spec:
  selector:
    app: meals
  ports:
    - name: meals
      protocol: TCP
      port: 3000
      targetPort: 3000
